const profiles = {
    "Aurèle":{
        "country":["FR","CH"],
        "quote":"Arrêtez d'essayer de me corrompre. Si vous voulez des points dans la liste, venez les mériter au TSB!",
        "startgg":"f2a4ac27",
    },
    "PtitLee":{
        "country":["FR"],
        "quote":"C'est pas la Mowgli cup mais c'est quand même la loi de la jungle",
        "startgg":"cf0a8db9",
    },
    "crhk":{
        "country":["FR"],
        "quote":"Parfois l'instinct vaut mieux que la réflexion.",
        "startgg":"44fe6e10",
    },
    "Niabanh":{
        "country":["FR"],
        "quote":"Joue avec ton cœur!"
    },
    "Hayao": {
        "country":["JP"]
    },
    "Sho": {
        "country":["JP"]
    },
    "RX": {
        "country":["JP"]
    },
    "Tominaga": {
        "country":["JP"]
    },
    "Genki": {
        "country":["JP"]
    },
    "Boss": {
        "country":["JP"]
    },
    "Oryu": {
        "country":["JP"]
    },
    "Rikimaru": {
        "country":["JP"]
    },
    "D44Bas": {
        "country":["JP"]
    },
    "Momochi": {
        "country":["JP"]
    },
    "Haitani": {
        "country":["JP"]
    },
    "RF": {
        "country":["JP"]
    },
    "Umezono": {
        "country":["JP"]
    },
    "Dogura": {
        "country":["JP"]
    },
    "Go1": {
        "country":["JP"]
    },
    "MOV": {
        "country":["JP"]
    },
    "StormKubo": {
        "country":["JP"]
    },
    "Kuni":{
		"country":["JP"],
	},
	"Yomoda":{
		"country":["JP"],
	},
    "ChiRithy": {
        "country":["CA"]
    },
    "PTS1": {
        "country":["CA"]
    },
    "KyoKuji": {
        "country":["CA"]
    },
    "Psychochronic":{
        "country":["CA"],
    },
    "Makaveli": {
        "country":["CH"]
    },
    "Captain Honest":{
		"country":["CH"],
		"quote":"Il n'y a pas le feu au lac ",
		"startgg":"9733c30a",
	},
    "Z3rog":{
        "country":["SE"],
    },
    "Fjaza":{
        "country":["SE"],
        "quote":"Let Me Denjin Your Life",
		"startgg":"b647a7df",
    },
    "TheArpeggiator":{
        "country":["SE"],
    },
    "GodflashThunder":{
        "country":["SE"],
    },
    "RC":{
        "country":["SE"],
    },
    "Cyrox":{
        "country":["SE"],
    },
    "Studs":{
		"country":["SE"],
		"quote":"You play to win the game.",
		"startgg":"115488eb",
	},
    "Cactu":{
        "country":["GB"],
        "quote":"I'm here to Kara grab & eat pastry but your boulangerie is closed...",
		"startgg":"5bc752d7",
    },
    "cosmonaut":{
		"country":["GB"],
		"quote":"I'm long and strong! To challenge me would be so wrong!",
		"startgg":"e9b5d3fa",
	},
    "3J":{
        "country":["GB"],
    },
    "Azz":{
        "country":["GB"],
    },
    "Farhann":{
        "country":["GB"],
    },
    "ShinGeorge":{
        "country":["GB"],
    },
    "Scotty2salty":{
        "country":["GB"],
    },
    "Harley":{
        "country":["GB"],
    },
    "GucciSuit":{
        "country":["GB"],
    },
    "Tamraz":{
        "country":["GB"],
    },
    "CrimeInal":{
        "country":["GB"],
    },
    "RyanHart":{
        "country":["GB"],
    },
    "Percy":{
        "country":["GB"],
    },
    "VileIsland":{
		"country":["GB"],
		"quote":"LIVIN' LA VIDA LOW TIER!",
		"startgg":"3113241e",
	},
    "Klaww":{
        "country":["IT"],
    },
    "Biollo":{
        "country":["IT"],
    },
    "Jaxsaon":{
		"country":["IT"],
		"startgg":"b3a98e1f",
	},
    "VeneziaCHUNLI":{
		"country":["IT"],
		"quote":"?!.........",
		"startgg":"80d02eb5",
	},
    "Jck":{
		"country":["IT"],
		"startgg":"95dd7b6e",
	},
    "Maurya":{
        "country":["US"],
    },
    "Exodus":{
        "country":["US"],
    },
    "Lance":{
        "country":["US"],
    },
    "JustinWong":{
        "country":["US","CA"],
    },
    "Aliartguy":{
        "country":["GB"],
    },
    "Exa":{
        "country":["BE"],
    },
    "Kenpachi":{
        "country":["BE"],
    },
    "Tichoune":{
        "country":["BE"],
    },
    "Bossomat":{
        "country":["DE"],
    },
    "Zouni":{
        "country":["MA"],
    },
    "Nindo":{
        "country":["NL"],
    },
    "Mikazuki":{
		"country":["BG"],
		"quote":"Red Block Buster Winner",
	},
    "rokich":{
		"country":["BG"],
		"startgg":"f6edc394",
	},
	"shadyAF":{
		"country":["BG"],
		"quote":"Lud li si? ",
		"startgg":"588a82ef",
	},
    "ca1Nne":{
		"country":["BG"],
		"startgg":"c474a000",
	},
    "Cartola":{
		"country":["ES"],
		"startgg":"8ee430cb",
	},
    "Otana":{
        "country":["FR"],
        "startgg":"6d9282d8",
    },
    "YaZ":{
        "country":["FR"],
        "quote":"To take or to tech the throw —that is the question.",
		"startgg":"e2221828",
    },
    "Victor":{
        "country":["FR"],
    },
    "Mymoza":{
        "country":["FR"],
        "quote":"ça se met bien avec les foreigner",
		"startgg":"d551c263",
    },
    "MLK":{
        "country":["FR"],
        "quote":"Facile ce jeu.",
        "startgg":"f74cb69e",
    },
    "BillyKane":{
        "country":["FR"],
        "quote":"Le Grand Pope",
		"startgg":"d9ca036e",
    },
    "Massi":{
        "country":["FR"],
    },
    "Nikola":{
        "country":["FR"],
        "quote":"Хајде да се боримо као џентлмени!",
		"startgg":"35fa15c9",
    },
    "Farouk":{
        "country":["FR"],
    },
    "Daolicious":{
        "country":["FR"],
    },
    "Kiji":{
        "country":["FR"],
    },
    "MounB":{
        "country":["FR","JP"],
    },
    "Marko":{
        "country":["FR","JP"],
    },
    "Jehan":{
        "country":["FR"],
    },
    "Pingouin":{
        "country":["FR"],
        "quote":"Attention à la mousse!",
		"startgg":"52c63832",
    },
    "Coccis":{
        "country":["FR"],
        "startgg":"fc809a27",
    },
    "Dobodry":{
        "country":["FR"],
    },
    "Lynohaz":{
        "country":["FR"],
        "startgg":"92b25bde",
    },
    "R":{
        "country":["FR"],
    },
    "Odasan":{
        "country":["FR"],
        "quote":"Left ? Right ? Not my problem.",
		"startgg":"2a33c77b",
    },
    "AlabhamaMan":{
        "country":["FR"],
    },
    "Boulben":{
        "country":["FR"],
        "quote":"Pose les deux pieds en canard c'est la Chun Li qui redémarre",
		"startgg":"424fdf39",
    },
    "Sikaryu":{
        "country":["FR"],
        "quote":"Je parle avec mes points 😁👍🏾",
    },
    "Jason":{
        "country":["FR"],
    },
    "Zheng":{
        "country":["FR","CN"],
    },
    "Cardb0xx":{
        "country":["FR"],
        "quote":"\"Ça fait les combos just frame mais ça sait pas hk duck super\" - MLK",
		"startgg":"f278623b",
    },
    "Lithlad":{
        "country":["FR"],
    },
    "Fardec":{
        "country":["FR"],
    },
    "Rechiku":{
        "country":["FR"],
    },
    "Zyul":{
        "country":["FR"],
        "startgg":"0ce41f54",
    },
    "MaxLeSac":{
        "country":["FR"],
        "quote":"3.3 mon gars BGOTU",
		"startgg":"d3addb00",
    },
    "DonYann":{
        "country":["FR"],
    },
    "Sogeking":{
        "country":["FR"],
    },
    "Auber":{
        "country":["FR"],
        "quote":"Tu es fada je crains dégun, je vous prends tous ici, un par un",
		"startgg":"02be1006",
    },
    "Slim":{
        "country":["FR"],
    },
    "Floodman":{
        "country":["FR"],
    },
    "Arq":{
        "country":["FR"],
        "quote":"au moins j'ai pris un round",
		"startgg":"1e82331e",
    },
    "Raiser":{
        "country":["FR"],
    },
    "Indy":{
        "country":["FR"],
    },
    "Livid":{
        "country":["FR"],
        "quote":"♪",
    },
    "ChapeauRéglisse":{
        "country":["FR"],
    },
    "SonicSan":{
        "country":["FR"],
    },
    "Izil":{
        "country":["FR","GB"],
    },
    "Dan":{
        "country":["FR"],
    },
    "MetalBrasier":{
        "country":["FR"],
    },
    "Mwouisman":{
        "country":["FR"],
    },
    "Nach":{
        "country":["FR"],
    },
    "Yamazaki93":{
        "country":["FR"],
    },
    "Chiisai":{
        "country":["FR"],
    },
    "Gorka":{
        "country":["FR"],
    },
    "Azerty":{
        "country":["FR"],
    },
    "Kamess":{
        "country":["FR"],
    },
    "Nehro":{
        "country":["FR"],
    },
    "Virus":{
        "country":["FR"],
    },
    "Rapeurtugais":{
        "country":["FR"],
    },
    "Grouflon":{
        "country":["FR"],
    },
    "Nazao":{
        "country":["FR"],
    },
    "TKO":{
        "country":["FR"],
    },
    "Hilight":{
        "country":["FR"],
        "quote":"Les super je les mets où je veux et c'est souvent dans la garde !",
		"startgg":"64bafa2d",
    },
    "Nighty":{
        "country":["FR"],
    },
    "Raven":{
        "country":["FR"],
    },
    "Rufio":{
        "country":["FR"],
    },
    "Solinvictus":{
        "country":["FR"],
    },
    "Piranha":{
        "country":["FR"],
    },
    "GTOMRick":{
        "country":["FR"],
    },
    "RoboQui":{
        "country":["FR"],
        "quote":"Spécialiste du denjin pas assez chargé",
		"startgg":"0a7460bf",
    },
    "Keizaal":{
        "country":["FR"],
    },
    "Mitch":{
        "country":["FR"],
        "quote":"Balayette!!!"
    },
    "TwiF":{
        "country":["FR"],
    },
    "Sanguine":{
        "country":["FR"],
    },
    "Isimorn":{
        "country":["FR"],
        "quote":"2HP into crush into avant MK",
		"startgg":"b0bedd01",
    },
    "Arno1":{
        "country":["FR"],
    },
    "fool":{
        "country":["FR"],
    },
    "MilesTheOne":{
        "country":["FR"],
    },
    "Touakak":{
        "country":["FR"],
    },
    "Gabou":{
        "country":["FR"],
    },
    "Luji":{
        "country":["FR"],
    },
    "Gagapa":{
        "country":["FR"],
    },
    "Neithan":{
        "country":["FR"],
    },
    "MPropre":{
        "country":["FR"],
    },
    "Tobitake":{
        "country":["FR"],
    },
    "Shin":{
        "country":["FR"],
        "startgg":"707c8d42",
    },
    "kupokupokupo":{
        "country":["FR"],
    },
    "BearArmy":{
        "country":["FR"],
    },
    "ChefBravo":{
        "country":["FR","ES"],
    },
    "Warner":{
        "country":["FR"],
        "quote":"Fiat Punto tkt !",
		"startgg":"1ee1f22e",
    },
    "Keikun":{
        "country":["FR"],
    },
    "Cheveuxlongs":{
        "country":["FR"],
    },
    "Rex":{
        "country":["FR"],
    },
    "Heavy":{
        "country":["FR"],
    },
    "Fredo":{
        "country":["FR"],
    },
    "Kakakokeokuku":{
        "country":["FR"],
    },
    "Pyrotek":{
        "country":["FR"],
    },
    "TMac14":{
        "country":["FR"],
    },
    "Yox":{
        "country":["FR","MX"],
    },
    "Morse":{
        "country":["FR"],
    },
    "Kalagan":{
        "country":["FR"],
    },
    "Gweilo":{
        "country":["FR"],
    },
    "Onigiri":{
        "country":["FR"],
    },
    "PaddyHacker":{
        "country":["FR"],
    },
    "Rafael":{
        "country":["FR"],
    },
    "Clint":{
        "country":["FR"],
    },
    "AngelKillah":{
        "country":["FR"],
    },
    "Omed":{
        "country":["FR"],
    },
    "Boxer":{
        "country":["FR"],
    },
    "Bob":{
        "country":["FR"],
    },
    "Pe1port":{
        "country":["FR"],
    },
    "Cheminot":{
        "country":["FR"],
    },
    "DoubleU":{
        "country":["FR"],
    },
    "Kikikirissx":{
        "country":["FR"],
    },
    "Pierrot":{
        "country":["FR"],
    },
    "Zarghatt":{
        "country":["FR"],
        "quote":"Me suis trompé de jeu, faites pas attention.",
		"startgg":"d1590049",
    },
    "Morphaman":{
        "country":["FR"],
    },
    "RyoKGU":{
        "country":["FR"],
    },
    "Pecheur":{
        "country":["FR"],
    },
    "Benjamin":{
        "country":["FR"],
    },
    "Miso":{
        "country":["FR"],
    },
    "PartyBrain5000":{
        "country":["FR"],
    },
    "Stef":{
        "country":["FR"],
    },
    "FirstSogeking":{
        "country":["FR"],
    },
    "Saverio":{
        "country":["FR"],
    },
    "Max":{
        "country":["FR"],
    },
    "Sangave":{
        "country":["FR"],
    },
    "Scavs":{
        "country":["FR"],
    },
    "Fryne":{
		"country":["FR"],
		"startgg":"9de7a20a",
	},
    "Prosk":{
		"country":["FR"],
		"quote":"Moi je suis plutôt manette",
		"startgg":"5dad7292",
	},
    "SayaZian":{
		"country":["FR"],
		"startgg":"565624ed",
	},
	"MM2":{
		"country":["FR"],
		"startgg":"6f8d8f21",
	},
    "Rockar":{
		"country":["FR"],
		"startgg":"eceac4e4",
	},
	"Vanille":{
		"country":["FR"],
		"quote":"Je fait grincer les chaises et les catapultes.",
		"startgg":"543291fe",
	},
    "NuclearLunch":{
		"country":["FR"],
		"startgg":"0b3ed058",
	},
    "Lana":{
		"country":["FR"],
		"quote":"Being serious is a bad habit!",
		"startgg":"443ddeae",
	},
    "VERi":{
		"country":["FR"],
		"startgg":"e8eb40ab",
	},
    "Mif":{
		"country":["FR"],
		"quote":"PdM",
		"startgg":"3b2b57aa",
	},
}
