const profiles = {
    "Aurèle":{
        "country":["FR","CH"],
        "quote":"Arrêtez d'essayer de me corrompre.",
        "startgg":"f2a4ac27",
    },
    "PtitLee":{
        "country":["FR"],
        "quote":"C'est pas la Mowgli cup mais c'est quand même la loi de la jungle",
        "startgg":"cf0a8db9",
    },
    "crhk":{
        "country":["FR"],
        "quote":"Parfois l'instinct vaut mieux que la réflexion.",
        "startgg":"44fe6e10",
    },
    "Niabanh":{
        "country":["FR"],
        "quote":"Joue avec ton cœur!",
        "startgg":"8b5185fe",
    },
    "Hayao": {
        "country":["JP"]
    },
    "Sho": {
        "country":["JP"]
    },
    "RX": {
        "country":["JP"]
    },
    "Tominaga": {
        "country":["JP"]
    },
    "Genki": {
        "country":["JP"]
    },
    "Boss": {
        "country":["JP"]
    },
    "Oryu": {
        "country":["JP"]
    },
    "Rikimaru": {
        "country":["JP"]
    },
    "D44Bas": {
        "country":["JP"]
    },
    "Momochi": {
        "country":["JP"]
    },
    "Haitani": {
        "country":["JP"]
    },
    "RF": {
        "country":["JP"]
    },
    "Umezono": {
        "country":["JP"]
    },
    "Dogura": {
        "country":["JP"]
    },
    "Go1": {
        "country":["JP"]
    },
    "MOV": {
        "country":["JP"]
    },
    "StormKubo": {
        "country":["JP"]
    },
    "Kuni":{
		"country":["JP"],
	},
	"Yomoda":{
		"country":["JP"],
	},
    "Taihei":{
		"country":["JP"],
		"quote":"Next Week!",
	},
    "PierrotLucifer":{
		"country":["JP"],
	},
    "Sugiyama":{
		"country":["JP"],
	},
    "Mimora":{
		"country":["JP"],
	},
    "TM":{
		"country":["JP"],
	},
    "ChiRithy": {
        "country":["CA"],
        "startgg":"3730695a",
    },
    "PTS1": {
        "country":["CA"],
        "startgg":"2ca48176",
    },
    "KyoKuji": {
        "country":["CA"]
    },
    "Psychochronic":{
        "country":["CA"],
    },
    "Jonas":{
        "country":["CA"],
		"quote":"A la recherche du respect!!!",
		"startgg":"0db32e6f",
	},
    "Makaveli": {
        "country":["CH"],
        "quote":"Watches, banks, cheese, chocolate, and 1 Gouki.",
		"startgg":"bb0896be",
    },
    "Captain Honest":{
		"country":["CH"],
		"quote":"Il n'y a pas le feu au lac ",
		"startgg":"9733c30a",
	},
    "Ghaust":{
		"country":["CH"],
		"quote":"Comment on joue arcade 😂",
		"startgg":"70c81ae8",
	},
    "Calimero4055":{
		"country":["CH"],
    },
    "Motivated!":{
		"country":["CH"],
    },
    "Bowli":{
		"country":["CH"],
    },
    "Z3rog":{
        "country":["SE","DE"],
        "quote":"知己知彼 百战不殆",
		"startgg":"db0c5fbe",
    },
    "P-Drum":{
        "country":["SE","DE"],
    },
    "Fjaza":{
        "country":["SE"],
        "quote":"Let Me Denjin Your Life",
		"startgg":"b647a7df",
    },
    "TheArpeggiator":{
        "country":["SE"],
    },
    "GodflashThunder":{
        "country":["SE"],
    },
    "RC":{
        "country":["SE"],
        "quote":"Jag tror på köttets lust och själens obotliga ensamhet",
		"startgg":"08746471",
    },
    "Cyrox":{
        "country":["SE"],
    },
    "Studs":{
		"country":["SE"],
		"quote":"You play to win the game.",
		"startgg":"115488eb",
	},
    "Oslo":{
		"country":["SE"],
		"quote":"Pick a top tier.- Sanford Kelly",
		"startgg":"e7cbbe40",
	},
    "Cactu":{
        "country":["GB"],
        "quote":"I'm here to Kara grab & eat pastry but your boulangerie is closed...",
		"startgg":"5bc752d7",
    },
    "cosmonaut":{
		"country":["GB"],
		"quote":"I'm long and strong! To challenge me would be so wrong!",
		"startgg":"e9b5d3fa",
	},
    "3J":{
        "country":["GB"],
        "quote":"Hayate, tsurugi, orochi, fukiage, karakusa; these are my weapons that will seal your fate! ",
		"startgg":"ce79f544",
    },
    "Azz":{
        "country":["GB"],
        "quote":"Lunch break, special herbs, fries and a sammich. Unleashed on the city, maximize damage",
		"startgg":"acd6b871",
    },
    "Farhann":{
        "country":["GB"],
    },
    "ShinGeorge":{
        "country":["GB"],
        "quote":"I have no idea what I'm doing",
		"startgg":"ee7c8cf6",
    },
    "Scotty2salty":{
        "country":["GB"],
    },
    "Harley":{
        "country":["GB"],
    },
    "GucciSuit":{
        "country":["GB"],
    },
    "Tamraz":{
        "country":["GB"],
    },
    "CrimeInal":{
        "country":["GB"],
    },
    "RyanHart":{
        "country":["GB"],
    },
    "Percy":{
        "country":["GB"],
    },
    "VileIsland":{
		"country":["GB"],
		"quote":"LIVIN' LA VIDA LOW TIER!",
		"startgg":"3113241e",
	},
    "Jazzerino":{
		"country":["GB"],
		"quote":"Dont get gripsed",
		"startgg":"918090b6",
	},
    "Yekrats":{
		"country":["GB"],
		"quote":"Whiff Tachi and a Dream..",
		"startgg":"4c873059",
	},
    "Bagel":{
		"country":["GB"],
    },
    "GoldmanJaqs":{
		"country":["GB"],
    },
    "Jewelbox":{
		"country":["GB"],
    },
    "Klaww":{
        "country":["IT"],
        "quote":"Give us the damn mona lisa back",
		"startgg":"ca00f5ab",
    },
    "Biollo":{
        "country":["IT"],
    },
    "Jaxsaon":{
		"country":["IT"],
		"startgg":"b3a98e1f",
	},
    "VeneziaCHUNLI":{
		"country":["IT"],
		"quote":"?!.........",
		"startgg":"80d02eb5",
	},
    "Jck":{
		"country":["IT"],
		"startgg":"95dd7b6e",
	},
    "Gillstolemyride":{
		"country":["IT"],
	},
    "Maurya":{
        "country":["US"],
    },
    "Exodus":{
        "country":["US"],
    },
    "Lance":{
        "country":["US"],
    },
    "FrankieBFG":{
        "country":["US"],
    },
    "Bubbles":{
        "country":["US"],
    },
    "KyoShiro":{
        "country":["US"],
    },
    "YetAnotherAstrid":{
        "country":["US"],
    },
    "JustinWong":{
        "country":["US","CA"],
    },
    "Aliartguy":{
        "country":["GB"],
    },
    "Exa":{
        "country":["BE"],
    },
    "Kenpachi":{
        "country":["BE"],
    },
    "Tichoune":{
        "country":["BE"],
    },
    "Vermeers":{
        "country":["BE"],
    },
    "Bossomat":{
        "country":["DE"],
    },
    "Zouni":{
        "country":["MA"],
    },
    "Nindo":{
        "country":["NL"],
        "quote":"Way of the ninja",
		"startgg":"c25d755c",
    },
    "AQH":{
		"country":["NL"],
		"quote":"Ik weet wannneer jouw knop drukt, mattie.",
		"startgg":"0d95d754",
	},
    "Nosferatu":{
		"country":["NL"],
		"startgg":"d7ee6529",
	},
    "SeldomSadSam":{
        "country":["NL"],
    },
    "Mikazuki":{
		"country":["BG"],
		"quote":"Red Block Buster Winner",
	},
    "Rokich":{
		"country":["BG"],
		"startgg":"f6edc394",
	},
	"ShadyAF":{
		"country":["BG"],
		"quote":"Lud li si? ",
		"startgg":"588a82ef",
	},
    "Ca1Nne":{
		"country":["BG"],
		"startgg":"c474a000",
	},
    "Cartola":{
		"country":["ES"],
		"startgg":"8ee430cb",
	},
    "Dioxin":{
		"country":["AE"],
		"startgg":"277e082c",
	},
    "Otana":{
        "country":["FR"],
        "startgg":"6d9282d8",
    },
    "YaZ":{
        "country":["FR"],
        "quote":"To take or to tech the throw —that is the question.",
		"startgg":"e2221828",
    },
    "Victor":{
        "country":["FR"],
    },
    "Mymoza":{
        "country":["FR"],
        "quote":"ça se met bien avec les foreigner",
		"startgg":"d551c263",
    },
    "MLK":{
        "country":["FR"],
        "quote":"Facile ce jeu.",
        "startgg":"f74cb69e",
    },
    "BillyKane":{
        "country":["FR"],
        "quote":"Le Grand Pope",
		"startgg":"d9ca036e",
    },
    "Massi":{
        "country":["FR"],
        "startgg":"246a0b3b",
    },
    "Nikola":{
        "country":["FR"],
        "quote":"Хајде да се боримо као џентлмени!",
		"startgg":"35fa15c9",
    },
    "Farouk":{
        "country":["FR"],
        "quote":"?? ???? ?????",
		"startgg":"b18ddf58",
    },
    "Daolicious":{
        "country":["FR"],
        "quote":"Siuuuuuuuuuuu",
		"startgg":"2fd17b13",
    },
    "Kiji":{
        "country":["FR"],
        "quote":"لا تكن مجنونا",
		"startgg":"d524cd97",
    },
    "MounB":{
        "country":["FR","JP"],
    },
    "Marko":{
        "country":["FR","JP"],
    },
    "Jehan":{
        "country":["FR"],
        "startgg":"9935685e",
    },
    "Pingouin":{
        "country":["FR"],
        "quote":"Attention à la mousse!",
		"startgg":"52c63832",
    },
    "Coccis":{
        "country":["FR"],
        "startgg":"fc809a27",
    },
    "Dobodry":{
        "country":["FR"],
        "quote":"J'aurais dû gagner le contest",
		"startgg":"d3b2a20f",
    },
    "Lynohaz":{
        "country":["FR"],
        "startgg":"92b25bde",
    },
    "R":{
        "country":["FR"],
    },
    "Odasan":{
        "country":["FR"],
        "quote":"Left ? Right ? Not my problem.",
		"startgg":"2a33c77b",
    },
    "AlabhamaMan":{
        "country":["FR"],
    },
    "Boulben":{
        "country":["FR"],
        "quote":"Pose les deux pieds en canard c'est la Chun Li qui redémarre",
		"startgg":"424fdf39",
    },
    "Sikaryu":{
        "country":["FR"],
        "quote":"Je parle avec mes points 😁👍🏾",
        "startgg":"01a106fc",
    },
    "Jason":{
        "country":["FR"],
    },
    "Zheng":{
        "country":["FR","CN"],
    },
    "Cardb0xx":{
        "country":["FR"],
        "quote":"\"Ça fait les combos just frame mais ça sait pas hk duck super\" - MLK",
		"startgg":"f278623b",
    },
    "Lithlad":{
        "country":["FR"],
        "quote":"C'est brouillon mais ça passe. ",
		"startgg":"4e88c9f0",
    },
    "Fardec":{
        "country":["FR"],
    },
    "Rechiku":{
        "country":["FR"],
    },
    "Zyul":{
        "country":["FR"],
        "startgg":"0ce41f54",
    },
    "MaxLeSac":{
        "country":["FR"],
        "quote":"3.3 mon gars BGOTU",
		"startgg":"d3addb00",
    },
    "DonYann":{
        "country":["FR"],
    },
    "Sogeking":{
        "country":["FR"],
    },
    "Auber":{
        "country":["FR"],
        "quote":"Tu es fada je crains dégun, je vous prends tous ici, un par un",
		"startgg":"02be1006",
    },
    "Slim":{
        "country":["FR"],
    },
    "Floodman":{
        "country":["FR"],
        "startgg":"f8760bd8",
    },
    "Arq":{
        "country":["FR"],
        "quote":"au moins j'ai pris un round",
		"startgg":"1e82331e",
    },
    "Raiser":{
        "country":["FR"],
    },
    "Indy":{
        "country":["FR"],
    },
    "Livid":{
        "country":["FR"],
        "quote":"♪ - Haute vertu, basse vertu, etc",
        "startgg":"e69ce980",
    },
    "ChapeauRéglisse":{
        "country":["FR"],
    },
    "SonicSan":{
        "country":["FR"],
    },
    "Izil":{
        "country":["FR","GB"],
    },
    "Dan":{
        "country":["FR"],
    },
    "MetalBrasier":{
        "country":["FR"],
        "quote":"oraindik bizirik nago, mutil",
		"startgg":"dde1c25e",
    },
    "Mwouisman":{
        "country":["FR"],
    },
    "Nach":{
        "country":["FR"],
    },
    "Yamazaki93":{
        "country":["FR"],
    },
    "Chiisai":{
        "country":["FR"],
    },
    "Gorka":{
        "country":["FR"],
    },
    "Azerty":{
        "country":["FR"],
    },
    "Kamess":{
        "country":["FR"],
    },
    "Nehro":{
        "country":["FR"],
    },
    "Virus":{
        "country":["FR"],
        "quote":"Royal au bar",
		"startgg":"e8f6f59d",
    },
    "Rapeurtugais":{
        "country":["FR"],
    },
    "Grouflon":{
        "country":["FR"],
    },
    "Nazao":{
        "country":["FR"],
    },
    "TKO":{
        "country":["FR"],
        "quote":"Stand strong, the show has just begun",
		"startgg":"6a7fdbe0",
    },
    "Hilight":{
        "country":["FR"],
        "quote":"Les super je les mets où je veux et c'est souvent dans la garde !",
		"startgg":"64bafa2d",
    },
    "Nighty":{
        "country":["FR"],
    },
    "Raven":{
        "country":["FR"],
        "quote":"Patate !",
		"startgg":"4d535709",
    },
    "Rufio":{
        "country":["FR"],
    },
    "Solinvictus":{
        "country":["FR"],
    },
    "Piranha":{
        "country":["FR"],
    },
    "GTOMRick":{
        "country":["FR"],
    },
    "RoboQui":{
        "country":["FR"],
        "quote":"Spécialiste du denjin pas assez chargé",
		"startgg":"0a7460bf",
    },
    "Keizaal":{
        "country":["FR"],
        "quote":"Gwelloc'h eo lazhañ ar bleiz evit bezañ lazhet gantañ.",
		"startgg":"6718d136",
    },
    "Mitch":{
        "country":["FR"],
        "quote":"Balayette!!!"
    },
    "TwiF":{
        "country":["FR"],
    },
    "Sanguine":{
        "country":["FR"],
    },
    "Isimorn":{
        "country":["FR"],
        "quote":"2HP into crush into avant MK",
		"startgg":"b0bedd01",
    },
    "Arno1":{
        "country":["FR"],
    },
    "fool":{
        "country":["FR"],
    },
    "MilesTheOne":{
        "country":["FR"],
    },
    "Touakak":{
        "country":["FR"],
    },
    "Gabou":{
        "country":["FR"],
    },
    "Luji":{
        "country":["FR"],
    },
    "Gagapa":{
        "country":["FR"],
    },
    "Neithan":{
        "country":["FR"],
        "quote":"Ce ryu mon gars",
		"startgg":"a8791beb",

    },
    "MPropre":{
        "country":["FR"],
    },
    "Tobitake":{
        "country":["FR"],
    },
    "Shin":{
        "country":["FR"],
        "startgg":"707c8d42",
    },
    "kupokupokupo":{
        "country":["FR"],
    },
    "BearArmy":{
        "country":["FR"],
    },
    "ChefBravo":{
        "country":["FR","ES"],
    },
    "Warner":{
        "country":["FR"],
        "quote":"Fiat Punto tkt !",
		"startgg":"1ee1f22e",
    },
    "Keikun":{
        "country":["FR"],
    },
    "Cheveuxlongs":{
        "country":["FR"],
    },
    "Rex":{
        "country":["FR"],
    },
    "Heavy":{
        "country":["FR"],
    },
    "Fredo":{
        "country":["FR"],
    },
    "Kakakokeokuku":{
        "country":["FR"],
    },
    "Pyrotek":{
        "country":["FR"],
    },
    "TMac14":{
        "country":["FR"],
    },
    "Yox":{
        "country":["FR","MX"],
    },
    "Morse":{
        "country":["FR"],
    },
    "Kalagan":{
        "country":["FR"],
    },
    "Gweilo":{
        "country":["FR"],
        "quote":"Protect Trans Lives !",
		"startgg":"a98bbf13",
    },
    "Onigiri":{
        "country":["FR"],
    },
    "PaddyHacker":{
        "country":["GB"],
    },
    "Rafael":{
        "country":["FR"],
    },
    "Clint":{
        "country":["FR"],
    },
    "AngelKillah":{
        "country":["FR"],
    },
    "Omed":{
        "country":["FR"],
    },
    "Boxer":{
        "country":["FR"],
    },
    "Bob":{
        "country":["FR"],
    },
    "Pe1port":{
        "country":["FR"],
    },
    "Cheminot":{
        "country":["FR"],
    },
    "DoubleU":{
        "country":["FR"],
    },
    "Kikikirissx":{
        "country":["FR"],
    },
    "Pierrot":{
        "country":["FR"],
    },
    "Zarghatt":{
        "country":["FR"],
        "quote":"Me suis trompé de jeu, faites pas attention.",
		"startgg":"d1590049",
    },
    "Morphaman":{
        "country":["FR"],
    },
    "RyoKGU":{
        "country":["FR"],
    },
    "Pecheur":{
        "country":["FR"],
    },
    "Benjamin":{
        "country":["FR"],
    },
    "Miso":{
        "country":["FR"],
    },
    "PartyBrain5000":{
        "country":["FR"],
    },
    "Stef":{
        "country":["FR"],
    },
    "FirstSogeking":{
        "country":["FR"],
    },
    "Saverio":{
        "country":["FR"],
    },
    "Max":{
        "country":["FR"],
    },
    "Sangave":{
        "country":["FR"],
    },
    "Scavs":{
        "country":["FR"],
    },
    "Fryne":{
		"country":["FR"],
		"startgg":"9de7a20a",
	},
    "Prosk":{
		"country":["FR"],
		"quote":"Moi je suis plutôt manette",
		"startgg":"5dad7292",
	},
    "SayaZian":{
		"country":["FR"],
		"startgg":"565624ed",
	},
	"MM2":{
		"country":["FR"],
		"startgg":"6f8d8f21",
	},
    "Rockar":{
		"country":["FR"],
		"startgg":"eceac4e4",
	},
	"Vanille":{
		"country":["FR"],
		"quote":"Je fait grincer les chaises et les catapultes.",
		"startgg":"543291fe",
	},
    "NuclearLunch":{
		"country":["FR"],
		"startgg":"0b3ed058",
	},
    "Lana":{
		"country":["FR"],
		"quote":"Being serious is a bad habit!",
		"startgg":"443ddeae",
	},
    "VERi":{
		"country":["FR"],
		"startgg":"e8eb40ab",
	},
    "Mif":{
		"country":["FR"],
		"quote":"PdM",
		"startgg":"3b2b57aa",
	},
    "Jojomasters":{
		"country":["FR"],
		"startgg":"928d2478",
	},
    "K":{
		"country":["FR"],
		"quote":"No Kick",
		"startgg":"13c5325b",
	},
    "Foo":{
		"country":["FR"],
		"quote":"J'ai jamais gagné un match, excepté une fois au chalet.",
		"startgg":"ee242d20",
	},
    "HikenNoGief":{
		"country":["FR"],
		"quote":"Un jour un Garou street battle a Lyon",
		"startgg":"63f43b96",
	},
    "TobyAbare":{
		"country":["FR"],
		"quote":"C'est comment pour tenraiha avec makoto ?",
		"startgg":"a6e58561",
	},
    "Tentacules":{
		"country":["FR"],
		"startgg":"085d80b1",
	},
    "TheFunkyweapon":{
		"country":["FR"],
		"quote":"je cherche mon rythme , mais fini surtout ko ",
		"startgg":"58f6a701",
	},
    "Quenshi":{
		"country":["FR"],
		"quote":"Ewi !",
		"startgg":"9e6b46b0",
	},
    "ManyManon":{
		"country":["FR"],
		"startgg":"9801b3bc",
	},
    "Bansheebot":{
		"country":["FR"],
		"quote":"Zabel c'est un peu comme chun li mais avec un imblocable",
		"startgg":"f28d98c7",
	},
    "Pandougui":{
		"country":["FR"],
		"quote":"",
		"startgg":"81d4d9a5",
	},
    "Zouzou":{
		"country":["FR"],
		"quote":"pépère le chaaat",
	},
    "orochikem":{
		"country":["FR"],
		"quote":"La justice!!!",
		"startgg":"4664ba9b",
    },
    "Eldready":{
		"country":["FR"],
    },
    "Parpaing":{
		"country":["FR"],
    },
    "Jirolondon":{
		"country":["FR"],
    },
    "Orochikem":{
		"country":["FR"],
    },
    "Shield":{
		"country":["FR"],
    },
    "MagicRider":{
		"country":["FR"],
    },
    "Bonnet":{
		"country":["FR"],
    },
    "Jujumag2x":{
		"country":["FR"],
    },
    "Yamato":{
		"country":["FR"],
    },
    "Frionel":{
		"country":["FR"],
    },
    "Kareem":{
		"country":["FR"],
    },
    "Lap1":{
		"country":["FR"],
    },
    "Phalel":{
		"country":["FR"],
    },
    "Baraki":{
		"country":["FR"],
    },
    "Ninjardin":{
		"country":["FR"],
    },
    "Akva":{
		"country":["FR"],
    },
    "Artvado":{
		"country":["FR"],
    },
    "Vikage":{
		"country":["FR"],
    },
    "Binouzator":{
		"country":["FR"],
    },
    "Razielle":{
		"country":["FR"],
    },
    "Makyutan":{
		"country":["FR"],
    },
    "LéoDeParis":{
		"country":["FR"],
    },
    "WonderBoite":{
		"country":["FR"],
    },
    "Tuxo":{
		"country":["FR"],
    },
    "Ibuprofene":{
		"country":["FR"],
    },
    "Brown":{
		"country":["FR"],
    },
    "SoMasta":{
		"country":["FR"],
    },
    "Likiminaj":{
		"country":["FR"],
    },
    "JeeLoo":{
		"country":["FR"],
    },
    }
