const p2p = {
    "name":"Press 2 Play",
    "shortname":"p2p",
    "bracket":"https://challonge.com/fr/ihqsoxxg",
    "org":["GuardImpact","FirstAttack"],
    "org_link":["https://twitter.com/GuardImpactVS","https://twitter.com/firstattackbzh"],
    "type":"minor",
    "vod":"https://www.youtube.com/watch?v=fjzceXmumm8",
    "year":"2019",
    "month":"April",
    "results":
    {
        "Mymoza":"1",
        "Niabanh":"2",
        "Victor":"3",
        "MounB":"4",
        "Kiji":"5",
        "MLK":"5",
        "crhk":"7",
        "Farouk":"7",
        "Aurèle":"9",
        "kupokupokupo":"9",
        "Livid":"9",
        "R":"9",
        "Boulben":"13",
        "MaxLeSac":"13",
        "PtitLee":"13",
        "Rechiku":"13",
        "Morphaman":"17",
        "Neithan":"17",
        "Raven":"17"
    }
};
